# Generated by Django 4.0.3 on 2022-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdminPortal', '0003_alter_courses_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='is_compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
